name: Snapcraft

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Fetching the release package
      run: wget "https://github.com/romactu/xboxcloud/releases/download/${{github.ref_name}}/geforcenow_${GITHUB_REF:11}_linux.snap" -O "geforcenow.snap"

    - uses: snapcore/action-publish@v1
      with:
        store_login: ${{ secrets.SNAPCRAFT_LOGIN }}
        snap: geforcenow.snap # ${{ steps.build.outputs.snap }}
        release: stable
