#!/bin/bash

if [[ ! -n "$DISABLE_WAYLAND" && -n "$WAYLAND_DISPLAY" ]]; then
  WAYLAND_OPTS="--enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland"
fi

exec "$SNAP/linux-unpacked/geforcenow" --no-sandbox --disable-seccomp-filter-sandbox $WAYLAND_OPTS "$@"